import turtle
myTurtle = turtle.Turtle()
myTurtle.color("black")
myTurtle.shape("turtle")
w = turtle.Screen()
w.bgcolor("#00CC00")
myTurtle.speed()
myTurtle.begin_fill()
myTurtle.fillcolor(255,70,14)
for i in range(2):
  myTurtle.forward(225)
  myTurtle.left(90)
  myTurtle.forward(50)
  myTurtle.left(90)
myTurtle.end_fill()
myTurtle.begin_fill()
myTurtle.fillcolor(255,255,255)
for i in range(2):
  myTurtle.forward(225)
  myTurtle.right(90)
  myTurtle.forward(50)
  myTurtle.right(90)
myTurtle.end_fill()
myTurtle.right(90)
myTurtle.forward(50)
myTurtle.left(90)
myTurtle.begin_fill()
myTurtle.fillcolor(2,112,28)
for i in range(2):
  myTurtle.forward(225)
  myTurtle.right(90)
  myTurtle.forward(50)
  myTurtle.right(90)
myTurtle.end_fill()
myTurtle.begin_fill()
myTurtle.fillcolor("#606060")
myTurtle.right(90)
myTurtle.forward(300)
myTurtle.right(90)
myTurtle.forward(10)
myTurtle.right(90)
myTurtle.forward(400)
myTurtle.right(90)
myTurtle.forward(10)
myTurtle.end_fill()
myTurtle.up()
myTurtle.right(90)
myTurtle.forward(100)
myTurtle.left(90)
myTurtle.forward(122.5)
myTurtle.down()
myTurtle.color("blue")
myTurtle.circle(25)
myTurtle.left(90)
for i in range(24):
  myTurtle.forward(25)
  myTurtle.right(165)
  myTurtle.forward(25)
  myTurtle.left(180)
myTurtle.hideturtle()
